language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
github_packages:
  - devtools
r_packages:
 - covr
 - stats
 - rmarkdown
 - knitr
 - devtools
 - forecast
 - locfit
 - jsonlite
 - trend
 - tseries
apt_packages:
  - libxml2-dev
sudo: required
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'
