language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
r_packages:
 - covr
 - rmarkdown
 - knitr
 - devtools
 - forecast
 - locfit
 - jsonlite
 - trend
 - tseries
apt_packages:
  - libxml2-dev
warnings_are_errors: false

